### ISSUE TITLE
Heart rate does not update 

### ISSUE THREAD

**Issue by feilo05** [geoffhuntoon/simple-customizable-clock#10]
**Describe the bug**
The heart rate number does not update at all after initial read. 

**To Reproduce**
Happens just as you load the watch face on versa 2

**Expected behavior**
Changes in real time according to the readings

**Additional context**
Love how simple looking and how customizable your watchface is. Keep up the good work. I hope to use yours in the near future once this bug is fixed.

**Comment by geoffhuntsgood** [comment]
I believe this has been addressed, and the fix will be available with the next release. There was a bug in how I was handling the body presence sensor and the heart rate sensor's interactions with each other. Thanks for downloading, and for pointing this out!

**Comment by geoffhuntsgood** [comment]
Resolved with release v1.1.0. This version will be available on the Fitbit app store as soon as the build is approved!
