### ISSUE TITLE
Steps not ypdating in real time on my fitbit

### ISSUE THREAD

**Issue by kathy63** [geoffhuntoon/simple-customizable-clock#14]
steps only appear when i sync my watch. They should auto calculate as I step. They use to until I selected this new clock face. **Describe the bug**
A clear description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior, for example:
- Change '....' setting
- Click on '....'
- Activate '....'

**Expected behavior**
A clear description of what you expected to happen.

**Additional context**
Anything else we need to know that might help?

**Comment by geoffhuntsgood** [comment]
Hello, @kathy63, I'm actively working on a solution to this problem!

**Comment by geoffhuntsgood** [comment]
I apologize for the delay on this! The update that fixes this issue is under review by Fitbit and will be released soon.
