### ISSUE TITLE
not able to build with fitbit studio...

### ISSUE THREAD

**Issue by timmpy** [geoffhuntoon/simple-customizable-clock#15]
Hi Geoff,

when i copy the files to the fitbit studio, i'm not able to build. As it states that it's missing a lot of files...

i really want your clockface on my new Sense, but it is not showing in the gallery so i wanted to side load via the SDK5.0 fitbit studio...

hope to hear from you...

**Comment by geoffhuntsgood** [comment]
Hello, @timmpy! There are a lot of breaking changes between SDKs 4 and 5, but I'm working on adding that build to support the Sense and Versa 3. It should be ready soon!

**Comment by timmpy** [comment]
Great thank for your support! Note, also with fitbit studio sdk4 I'm not able to build...

**Comment by geoffhuntsgood** [comment]
Ah! I misread the issue! This project can't be built in Fitbit Studio, as the studio doesn't support TypeScript. When I made the conversion, I moved out of Fitbit Studio and into my personal IDE (I use IntelliJ). There might still be a way to generate JavaScript files and include only those in a build that *would* work in the studio, so I'll take a look into that!

**Comment by timmpy** [comment]
@geoffhuntoon in the meanwhile i tried to do something myself, based on the clockface [Source](https://github.com/lincsanders/fitbit_stats_clock) . Only thing is almost no color selection and some few other things that i would like but unable to....

see my code here: [My Clockface](https://github.com/timmpy/Clockface-Versa3-Sense-stats) 

things to improve:
- More color selections
- circle around the stats with filling the circle depending how far the goal is reached.
- turn off enabling of seconds
- heart-beat icon speed should be some speed as the real heart-beat
- select color of heart-beat icon
- spO2 data and\or sleeping score should be in the stats.
- stress level (number) in the stats... 
- in stats place is still free
- can add another stat in the middle of the bottom (enough place)
 - create battery icon, fill battery based on the actual battery level %
This is just my personal wish-list so when I get more knowledge how to do this i hope i'm able to do this. ;-)

really looking forward to your clockface, which has almost all these features in!

best regards, a happy Sense owner!

**Comment by timmpy** [comment]
By The Way , lots of design and interesting talk overhere at discord: [Fitbit Community](https://community.fitbit.com/t5/SDK-Development/Join-the-Unofficial-Fitbit-Discord-Chat-Server/td-p/2184884)

**Comment by geoffhuntsgood** [comment]
Hey there, going to close this now but I'm going to check out the Discord for sure!
