### ISSUE TITLE
Change to celsius?

### ISSUE THREAD

**Issue by JB101JB** [geoffhuntoon/simple-customizable-clock#22]
Really like your clock face, thanks!  Was wondering if you can make it possible to change the temperature to Celsius?  Thanks!

**Comment by geoffhuntsgood** [comment]
Hello, @JB101JB ! I'm working on an update to the weather side of things that should address this. Apologies for the delay!

**Comment by geoffhuntsgood** [comment]
This is resolved in release 1.1.2. Thanks for your patience!
