### ISSUE TITLE
Steps not updated without sync

### ISSUE THREAD

**Issue by jillsan** [geoffhuntoon/simple-customizable-clock#25]
**Describe the bug**
The steps are not immediate updates as previously. When I look at my Fitbit board I can see I have taken more steps that is shown on the clock interface

**To Reproduce**
Steps to reproduce the behavior, for example:
- walk
- and see the interface have been updated
No it doesn’t show
Check Fitbit board - more steps then on the clock interface
Go back to clock interface - steps are now updated

**Expected behavior**
I expect the clock inter face to have updated steps all the time

**Additional context**
Anything else we need to know that might help?
My iPhone 8+ is updated as well as my apps

**Comment by geoffhuntsgood** [comment]
This has been addressed with version 1.1.1!
