### ISSUE TITLE
Colors not changing 

### ISSUE THREAD

**Issue by jabuggie** [geoffhuntoon/simple-customizable-clock#37]
I changed the color settings, selected a different face and then reloaded this face. Colors never changed from white. After the reload, I checked the setting and the colors I desired were still selected but the Versa face still only had white colors.

**Comment by geoffhuntsgood** [comment]
Apologies for the delay in response! This is unusual. Could I ask what model of phone and what Fitbit you're using?

**Comment by geoffhuntsgood** [comment]
@jabuggie I'm going to close this issue, but please let me know if you're still experiencing problems or if there are any other persistent issues. One thing to try is to completely delete the watch face using your Fitbit app, then installing it again from scratch.

**Comment by jabuggie** [comment]
Good evening Geoff,

I am still not able to change the colors. I tried deleting the face and downloading again. (I unsaved the face which was the closest I could to deleting.) It did not change anything. I have take screenshots of my settings as well as the clock face. Thank you for looking into it. 

All the best,
James Buggie
(702) 521-1359

**Comment by geoffhuntsgood** [comment]
Thanks for the response! Let me reopen this issue, this merits looking more into.

**Comment by geoffhuntsgood** [comment]
Version 1.2.1 is currently under review by Fitbit - it will add a toggle button on the settings page on your phone that will manually reset all of your settings for this clock face. I apologize for the inconvenient solution but I *think* this reset is the best way to solve this issue. I'll let you know as soon as 1.2.1 is released!

**Comment by geoffhuntsgood** [comment]
Updates to this issue will be posted in #55 .

**Comment by jabuggie** [comment]
Hi Geoff,

I am not sure where to find this manual reset. I also don’t know if I am deleting the face correctly. I am unsaving the face and then reselecting it from the shop. It is currently unusable now. This is what my clock face looks like. 

 

All the best,
James Buggie
(702) 521-1359

**Comment by geoffhuntsgood** [comment]
Hello, James! The update is still under review by Fitbit. I'll let you know in #55 as soon as it's approved and published. When it's approved, you should see the reset appear in the settings page for the clock face on your phone.
