### ISSUE TITLE
only showing date and time

### ISSUE THREAD

**Issue by ktdavo** [geoffhuntoon/simple-customizable-clock#43]
Hi, when I select this clock face, it won’t show up on my watch screen properly. It only shows the time and day and none of the rings. It also doesn’t change the colours when I select them on the Fitbit app. The first time I put the watch face on it worked fine but I have tried a couple of times to get it on again and it hasn’t worked

**Comment by geoffhuntsgood** [comment]
Hello! I apologize for the delay in getting back to you! Could you let me know what Fitbit and what phone you are using? Also, in the meantime, you can try completely deleting the watch face using the Fitbit app and then installing it again from scratch. Please let me know if there are any other issues!

**Comment by Utmtnman** [comment]
![20201230_201312](https://user-images.githubusercontent.com/76800658/103392634-2c371500-4adc-11eb-84a3-586d08dba056.jpg)
I have the same issue. Doesn't display right. Versa 2 with Samsung Galaxy S8. I tried totally removing and reinstalling with no luck.

**Comment by geoffhuntsgood** [comment]
Version 1.2.1 is currently under review by Fitbit - it will add a toggle button on the settings page on your phone that will manually reset all of your settings for this clock face. I apologize for the inconvenient solution but I *think* this reset is the best way to solve this issue. I'll let you know as soon as 1.2.1 is released!

**Comment by geoffhuntsgood** [comment]
Updates to this issue will be posted in #55 .
