### ISSUE TITLE
Temperature not updating unless manual sync done

### ISSUE THREAD

**Issue by jefff54** [geoffhuntoon/simple-customizable-clock#46]
**Describe the bug**
Temperature on clock face is not updating automatically.  Temperature will only update if I perform a sync function in the Fitbit app on my phone.  The temp on the clock face expires after a time and is shown as "--".  Once I sync device with phone, temperature again displays

**Comment by geoffhuntsgood** [comment]
Hello, and apologies for the delay! I have a big update coming soon that *should* fix the issues some people were experiencing with weather updates. I'm marking this as resolved for now, but please let me know if there are any other issues.
