### ISSUE TITLE
Color won't change/only date and time

### ISSUE THREAD

**Issue by Sbuchanan87** [geoffhuntoon/simple-customizable-clock#53]
The first time I used this clock face worked perfectly and loved it. When I went to use it again the color wouldn't change and I could only see the date, time and heart rate.  There is also a black circle is th upper left hand corner with a white number 29 next to it. Was hoping this bug can be fixed because I really liked this face.

**Comment by geoffhuntsgood** [comment]
Hello! I sincerely apologize for the inconvenience, and I'm glad you like the clock face! Just in case you haven't already, could you try completely uninstalling and reinstalling? If you've tried that, could I get a little more info from you - what kind of Fitbit you have and what kind of phone you're using with it? Thank you!

**Comment by Sbuchanan87** [comment]
I have tried doing that a couple of times and still won't change. I have
the Fitbit versa and an Samsung galaxy s10.

**Comment by geoffhuntsgood** [comment]
Sounds good - I'll do a little research and see what I can do to fix this. I'll get back to you as soon as I can!

**Comment by Sbuchanan87** [comment]
Awesome, thank you so much!

**Comment by jehorizon** [comment]
I’m having the same problem. 
Versa and iPhone 8’s. Tried uninstalling and reinstalling but no help. This just started today after months of use when I put the watch on charge. Could it be related to the 12/22 release? I love this watch face so I hope it can be fixed.

**Comment by jehorizon** [comment]
![Uploading image.jpg…]()

**Comment by geoffhuntsgood** [comment]
Version 1.2.1 is currently under review by Fitbit - it will add a toggle button on the settings page on your phone that will manually reset all of your settings for this clock face. I apologize for the inconvenient solution but I *think* this reset is the best way to solve this issue. I'll let you know as soon as 1.2.1 is released!

**Comment by geoffhuntsgood** [comment]
Updates to this issue will be posted in #55 .
