### ISSUE TITLE
Watchface “stuck”

### ISSUE THREAD

**Issue by Mmaiorana** [geoffhuntoon/simple-customizable-clock#54]
Watchface is still telling time but the battery percentage is jumbled and the colors aren’t changing. See attached photo. I changed the time color to blue also. 

**To Reproduce**
Turn screen on, try activating a new color for something. 

**Expected behavior**
A clear picture of the battery percentage and the customizable colors. 
![image](https://user-images.githubusercontent.com/76829572/103432800-fe250400-4bb3-11eb-9a24-aa77ce717e7b.jpg)

**Comment by geoffhuntsgood** [comment]
Hello! This is a known issue and I'm working on a solution! Thanks for your patience

**Comment by geoffhuntsgood** [comment]
Version 1.2.1 is currently under review by Fitbit - it will add a toggle button on the settings page on your phone that will manually reset all of your settings for this clock face. I apologize for the inconvenient solution but I *think* this reset is the best way to solve this issue. I'll let you know as soon as 1.2.1 is released!

**Comment by geoffhuntsgood** [comment]
Updates to this issue will be posted in issue #55 .
